services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"  # Exposes port 5678 to the host
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh
      #REPLACE!!!! -Webhook MUST match subdomain
      - WEBHOOK_URL=https://n8n.saindeco.vn
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files  #maps a folder for local files

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
